config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ChinaCity::Engine => '/china_city'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'
  get 'catagory/:catagory_id' => 'welcome#list_posts', as: :catagory
  get 'catagory/:catagory_id/post/:post_id' => 'welcome#show_post', as: :post
  get 'station/:id/order' => 'station#order', as: :order
  get 'station/:id/step/:type' => 'station#step', as: :step

end

app/controllers/welcome_controller.rb
class WelcomeController < FrontBaseController
  ## 主页
  def index
    set_nav_field
  end

  ## 文章列表页
  def list_posts
    set_nav_field
    @catagory = Catagory.find(params[:catagory_id])
    # TODO dairg 404共通页面处理
  end

  ## 文章明细页
  def show_post
    set_nav_field
    @catagory = Catagory.find(params[:catagory_id])
    @post = Post.find(params[:post_id])
    # 如果post不是发布状态，那么返回404
    raise ActiveRecord::RecordNotFound unless @post.status_published?
    @pre_post = @post.pre_published_post
    @next_post = @post.next_published_post
  end

  ## 预约
  # TODO dairg 暂时放到这里
  def order
    set_nav_field
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def current_nav_class(path)
    current_path = request.original_fullpath
    if path == '/'
      current_path == path ? 'active' : ''
    else
      current_path.start_with?(path) ? 'active' : ''
    end
  end
end

app/views/welcome/_sidebar.html.erb
          <div class="bs-sidebar hidden-print affix" role="complementary">
            <ul class="nav bs-sidenav">
            <% @catagories.each do |catagory|  %>
              <li class="<%= catagory.id == @catagory.id ? 'active' : ''%>">
                <%= link_to catagory.name, catagory_path(catagory) %>
              </li>
            <% end %>
            </ul>
          </div>

app/views/welcome/index.html.erb
    <style>
      #main-content {
        background: url(<%= asset_path 'main_bg_image.png.bak' %>)
                    repeat-x transparent 50% 50%;
        height: 400px;
        width: 100%;
        color: white;
        text-align: center;
      }

      #main-content .bottom {
        margin: auto;
        margin-top: 60px;
      }

      #nav_circle {
        text-align: center;
      }

    </style>

    <!-- jumbotron -->
    <div id="main-content" class="jumbotron wrapped-content">
      <div class="container">
        <h1 style="font-size:50px; margin-top:50px;">一站式服务</h1>
        <h2 style="margin-top:30px;">
          <p>轻松预约，不用排队，个性服务，保您满意</p>
          <div class="bottom clearfix">
            <p>
            <a class="btn btn-lg btn-primary" href="<%= order_path(1) %>" role="button" style="font-size:30px;">在线预约检车 &raquo;</a>
            </p>
          </div>
        </h2>
      </div>
    </div>
    <!-- END jumbotron -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div id="nav_circle" class="container marketing wrapped-content">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <div class="big-nav-icon-info"></div>
          <h2>手机预约</h2>
          <p>ios, android应用.</p>
          <p><a class="btn btn-success" href="#" role="button">进入 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <div class="big-nav-icon-info"></div>
          <h2>电话预约</h2>
          <p>拨打400-400-400.</p>
          <p><a class="btn btn-success" href="#" role="button">进入 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <div class="big-nav-icon-info"></div>
          <h2>官方微信</h2>
          <p>扫一扫，关注我们.</p>
          <p><a class="btn btn-success" href="#" role="button">进入 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->

app/views/welcome/list_posts.html.erb
    <style>
      #main-content {
        margin-top: 50px;
        text-align: left;
      }
    </style>

    <div id="main-content" class="container marketing wrapped-content">

      <div class="row">
        <div class="col-md-3">
          <%= render "sidebar" %>
        </div><!-- /.col -->

        <div class="col-md-9" style="min-height: 300px;">
          <div class="info-list list-group">
            <% @catagory.posts.published.each do |post| %>
            <a href="<%= post_path(@catagory, post) %>" class="list-group-item">
              <%= post.title %>
              <span class="tips-date pull-right">
                <em><%= l(post.updated_at.to_date) %></em>
              </span>
            </a>
            <% end %>
          </div>
        </div>
      </div><!-- /.row -->
    </div>

app/views/welcome/show_post.html.erb
    <style>
      #main-content {
        margin-top: 50px;
        text-align: left;
      }
    </style>

    <div id="main-content" class="container marketing wrapped-content">

      <div class="row">
        <div class="col-md-3">
          <%= render "sidebar" %>
        </div><!-- /.col -->

        <div class="col-md-9 info-list post" style="min-height: 300px;">
          <div class="title">
            <h4 class="text-center"><%= @post.title %></h4>
            <p class="text-center tips-date">
              <em><%= l(@post.updated_at.to_date) %></em>
            </p>
            <% if @pre_post.present? %>
            <span class="pull-left">
              <small>
                <a href="<%= post_path(@catagory, @pre_post) %>">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                  <%= "#{t('views.action.pre_post')}#{@pre_post.title}" %>
                </a>
              </small>
            </span>
            <% end %>
            <% if @next_post.present? %>
            <span class="pull-right">
              <small>
                <a href="<%= post_path(@catagory, @next_post) %>">
                  <%= "#{t('views.action.next_post')}#{@next_post.title}" %>
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </small>
            </span>
            <% end %>
            <div class="clearfix"></div>
          </div>
          <div class="content">
            <%= @post.content.html_safe %>
          </div>
        </div>
      </div><!-- /.row -->
    </div>