config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ChinaCity::Engine => '/china_city'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'
  get 'catagory/:catagory_id' => 'welcome#list_posts', as: :catagory
  get 'catagory/:catagory_id/post/:post_id' => 'welcome#show_post', as: :post
  get 'station/:id/order' => 'station#order', as: :order
  get 'station/:id/step/:type' => 'station#step', as: :step

end

app/models/station.rb
class Station < ActiveRecord::Base

  extend Enumerize

  after_initialize :init

  ## Scopes
  default_scope { order(created_at: :asc) }
  scope :waiting, -> { with_status(:waiting) }
  scope :reviewed, -> { with_status(:reviewed) }
  scope :rejected, -> { with_status(:rejected) }
  scope :locked, -> { with_status(:locked) }
  scope :default_order, -> { order(created_at: :asc) }

  ## Validates
  validates :name, presence: true, length: { maximum: 20 }
  validates :province, presence: true
  validates :city, presence: true
  validates :district, presence: true
  validates :address, presence: true
  validates :telephone, presence: true
  enumerize :status, in: Car::Code::STATION_STATUS, default: :waiting, predicates: { prefix: true }, scope: true

  def init
    # 默认陕西省
    self.province = '610000'
  end
end

app/controllers/station_controller.rb
## 车检站
class StationController < FrontBaseController

  ## 一览
  def list
    set_nav_field
  end

  ## 预约
  # TODO dairg 暂时放到这里
  def order
    set_nav_field
    @steps = steps
    @current_step = steps.first
    session[:current_step] = @current_step
  end

  def step
    set_nav_field
    @steps = steps
    @current_step = session[:current_step]
    if params[:type] == 'next'
      @current_step = steps[steps.index(@current_step)+1] || steps.first
    elsif params[:type] == 'pre'
      @current_step = steps[steps.index(@current_step)-1]
    end
    session[:current_step] = @current_step

    render :order
  end

private
  def steps
    %w[select_station select_date basic_info confirmation success]
  end

end

app/views/station/_form_step_basic_info.html.erb
  <div class="form-group">
    <label for="inputCarNo" class="col-sm-2 control-label">车牌号</label>
    <div class="col-sm-6">
      <div class="input-group">
        <span class="input-group-addon">陕</span>
        <input type="text" class="form-control" id="inputCarNo" placeholder="AXXXXX">
      </div>
    </div>
  </div>

app/views/station/_form_step_confirmation.html.erb
<div class="confirmation">
  <div class="panel panel-info">
    <div class="panel-heading">基本信息</div>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-sm-3 control-label">车牌号</label>
        <div class="col-sm-9">
          <p class="form-control-static important-info">陕A12345</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">手机号</label>
        <div class="col-sm-9">
          <p class="form-control-static">18100000000</p>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-info">
    <div class="panel-heading">预约信息</div>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-sm-3 control-label">预约车检站</label>
        <div class="col-sm-9">
          <p class="form-control-static important-info">东郊车检站</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">地址</label>
        <div class="col-sm-9">
          <p class="form-control-static">东郊XXX路XX号</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">联系电话</label>
        <div class="col-sm-9">
          <p class="form-control-static">400-400-400</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">预约时间</label>
        <div class="col-sm-9">
          <p class="form-control-static important-info">2014年6月5日 星期五 上午8:00-10:00</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/station/_form_step_select_date.html.erb
                    <div class="row">
                        <div class="form-left">Email *</div>
                        <div class="form-right"><input type="text" id="email" name="email" class="form-input" /></div>
                        <div class="form-error"></div>
                    </div>
                    <div class="row">
                        <div class="form-left">Mobile No</div>
                        <div class="form-right"><input type="text" id="mobile" name="mobile" class="form-input" /></div>
                        <div class="form-error"></div>
                    </div>

app/views/station/_form_step_select_station.html.erb
          <div class="btn-group-vertical station-list" data-toggle="buttons">
            <label class="btn btn-default station-item">
              <input type="radio" name="options" id="option1">
              <p class="name">东郊车检所</p>
              <p>地址：东郊XX路189号     <a>地图</a></p>
              <p>电话：18900000000</p>
            </label>
            <label class="btn btn-default station-item">
              <input type="radio" name="options" id="option2">
              <p class="name">南郊车检所</p>
              <p>地址：南郊XX路289号     <a>地图</a></p>
              <p>电话：28900000000</p>
            </label>
            <label class="btn btn-default station-item">
              <input type="radio" name="options" id="option3">
              <p class="name">西郊车检所</p>
              <p>地址：西郊XX路389号     <a>地图</a></p>
              <p>电话：38900000000</p>
            </label>
          </div>

app/views/station/_form_step_success.html.erb
<div class="success">
  <div class="alert alert-success">恭喜您！您已经预约成功!</div>
  <div class="panel panel-info">
    <div class="panel-heading">预约信息</div>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-sm-3 control-label">预约流水号</label>
        <div class="col-sm-9">
          <p class="form-control-static important-info">J567234898784</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">车牌号</label>
        <div class="col-sm-9">
          <p class="form-control-static">陕A12345</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">手机号</label>
        <div class="col-sm-9">
          <p class="form-control-static">18100000000</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">预约车检站</label>
        <div class="col-sm-9">
          <p class="form-control-static">东郊车检站</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">地址</label>
        <div class="col-sm-9">
          <p class="form-control-static">东郊XXX路XX号</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">联系电话</label>
        <div class="col-sm-9">
          <p class="form-control-static">400-400-400</p>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-3 control-label">预约时间</label>
        <div class="col-sm-9">
          <p class="form-control-static">2014年6月5日 星期五 上午8:00-10:00</p>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-info">
    <div class="panel-heading">温馨提示</div>
    <div class="panel-body">
      <ul>
        <li>1.请您准时到达指定地点进行车检.</li>
      </ul>
    </div>
  </div>
</div>

app/views/station/order.html.erb
<% content_for :head_stylesheet do %>
  <%= stylesheet_link_tag 'front/order', media: 'all', 'data-turbolinks-track' => true %>
<% end %>
<% content_for :head_javascript do %>
  <%= javascript_include_tag 'front/order', 'data-turbolinks-track' => true %>
<% end %>
<style>
  #main-content {
    margin-top: 50px;
    text-align: left;
  }
</style>

<div id="main-content" class="container marketing wrapped-content">

  <div class="row inner">
    <div class="payStep0<%=@steps.index(@current_step) + 1%>">
      <ul class="payOrderSteps clear">
        <li class="step1">1.选择车检站</li>
        <li class="step2">2.选择检车时间</li>
        <li class="step3">3.填写基本信息</li>
        <li class="step4">4.确认预约信息</li>
        <li class="step5">5.预约成功</li>
      </ul>
    </div>
    <div class="step-content">
      <div class="col-md-9 step-form-left"> 
        <div class="main-form">
          <form class="form-horizontal" role="form">
          <%= render "form_step_#{@current_step}" %>
          </form>
        </div>
        <div class="left-box action">
          <% if @current_step == 'confirmation' %>
            <div style="text-align: center;">
              <a href="<%= step_path(1, :next)%>" class="btn btn-danger btn-lg">提交预约信息</a>
            </div>
          <% elsif @current_step == 'success' %>
            <div style="text-align: center;">
            <a href="<%= step_path(1, :pre)%>" class="btn btn-success">打印</a>
            <a class="btn btn-success">发送信息到手机</a>
          </div>
          <% else %>
            <a href="<%= step_path(1, :pre)%>" class="btn btn-default pull-left">上一步</a>
            <a href="<%= step_path(1, :next)%>" class="btn btn-primary btn-lg pull-right">下一步</a>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
      <div class="col-md-3 step-form-right"> 
        <div class="right-box order-tip-info">
          <p class='title'>预约信息</p>
          <hr>
          <div class='tip-group'>
            <p class='tip-label'>车牌</p>
            <p class='tip-value important-info'>陕A88888</p>
          </div>
          <div class='tip-group'>
            <p class='tip-label'>车检所</p>
            <p class='tip-value important-info'>西安东郊车检所</p>
          </div>
          <div class='tip-group'>
            <p class='tip-label'>预约时间</p>
            <p class='tip-value important-info'>2014年6月5日 星期五 上午8:00-10:00</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>